# https://imgtlk.appspot.com/ and https://imgtlk.com and https://www.imgtlk.com
# Develop: dev_appserver.py .
# Deploy: gcloud app deploy --project imgtlk

runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.+)
  static_files: public/\1
  upload: public/(.*)
  secure: always
- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always
# - url: /(.*)
#   script: 404.app
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?
